report tpm checks failure in the summary log
Signed-off-by: Shahriyar Jalayeri <shahriyar@zededa.com>

diff --git a/pkg/mkverification-raw-efi/verify b/pkg/mkverification-raw-efi/verify
--- a/pkg/mkverification-raw-efi/verify
+++ b/pkg/mkverification-raw-efi/verify
@@ -420,6 +420,9 @@ fi
 if [ -c $TPM_DEVICE_PATH ]; then
    logmsg "TPM device is present, running some extra tests"
    /verifytpm.sh | tee -a "$REPORT/tpmchecks.log" >/dev/console 2>&1
+   if ! grep -q "TPM checks PASSED" "$REPORT/tpmchecks.log"; then
+      echo "TPM checks FAILED, check tpmchecks.log for details" >> "$REPORT/summary.log";
+   fi
 else
    logmsg "No TPM device, skipping extra TPM checks"
 fi
