add recover-tpm tool to debug container
This tool makes intercting with the TPM easier.
specifically, it can be used extract volume keys
from the TPM, but only in an encrypted format suitable
for inserting in a cloud controler.

Signed-off-by: Shahriyar Jalayeri <shahriyar@zededa.com>

diff --git a/pkg/debug/Dockerfile b/pkg/debug/Dockerfile
--- a/pkg/debug/Dockerfile
+++ b/pkg/debug/Dockerfile
@@ -8,14 +8,15 @@
 # has a fast path for stack unwinding. This also happens
 # to be a perfect place to put any other kind of debug info
 # into the package: see abuild/etc/abuild.conf.
-FROM lfedge/eve-alpine:1f7685f95a475c6bbe682f0b976f12180b6c8726 as build
-ENV BUILD_PKGS abuild curl tar make linux-headers patch g++ git gcc ncurses-dev autoconf
+FROM lfedge/eve-alpine:cbf02c2c126f210933ec9bdb142eb080b400fd76 as build
+ENV BUILD_PKGS abuild curl tar make linux-headers patch g++ git gcc ncurses-dev autoconf go
 # Feel free to add additional packages here, but be aware that
 # EVE's rootfs image can be no larger than 300Mb (and don't
 # forget to check on all supported architectures: e.g. arm64
 # binaries are typically larger and amd64 ones).
 # RUN apk add --no-cache gdb valgrind
-ENV PKGS openssl openssh-client openssh-server tini util-linux ca-certificates pciutils usbutils vim tcpdump perf strace iproute2-minimal curl
+ENV PKGS openssl openssh-client openssh-server tini util-linux ca-certificates \
+         pciutils usbutils vim tcpdump perf strace iproute2-minimal curl
 
 # These packages are not available on the riscv arch, so I have no idea how
 # deliver those, but still install them on other archs.
@@ -44,16 +45,27 @@ RUN apk add -p /out --allow-untrusted /home/builder/packages/*/musl-1.2*.apk
 ADD https://www.ezix.org/software/files/lshw-B.${LSHW_VERSION}.tar.gz lshw.tar.gz
 RUN tar -xzvf lshw.tar.gz
 
+# build lshw
 WORKDIR /
 COPY lshw/ lshw-B.${LSHW_VERSION}/
-
 WORKDIR /lshw-B.${LSHW_VERSION}
-
 RUN for patch in *.patch; do \
    patch -p1 < "$patch"; \
  done && \
  make -C src RPM_OPT_FLAGS=-DNONLS static && \
  cp src/lshw-static /out/usr/bin/lshw && strip /out/usr/bin/lshw
+
+# build the tpm-recovery tool
+WORKDIR /
+COPY recover-tpm/ recover-tpm/
+WORKDIR /recover-tpm
+SHELL ["/bin/ash", "-eo", "pipefail", "-c"]
+# hadolint ignore=SC2046
+RUN echo "Running go vet" && go vet ./... && echo "Running go fmt" && \
+    ERR=$(gofmt -e -l -s $(find . -name \*.go | grep -v /vendor/)) && \
+    if [ -n "$ERR" ] ; then echo "go fmt Failed - ERR: $ERR"; exit 1 ; fi
+RUN CGO_ENABLED=0 go build -ldflags "-s -w" -o recovertpm . && \
+    cp recovertpm /out/usr/bin/recovertpm
 
 # building hexedit
 WORKDIR /tmp/hexedit/hexedit-1.5
